Manak: manak::BenchmarkSuite Class Reference
manak::BenchmarkSuite Class Reference
Public Member Functions
BenchmarkSuite ()
BenchmarkSuite (const std::string &name)
~BenchmarkSuite ()
BenchmarkCase * AddCase (BenchmarkCase *obj)
BenchmarkSuite * AddSuite (BenchmarkSuite *suite)
bool Find (const std::string &name, std::list< BenchmarkCase * > &lbc)
BenchmarkSuite * GetCurrentSuite () const
bool LoadData (const std::string &name)
const std::string & Name () const
std::string & Name ()
bool Run (const std::string &uname="", const std::string &pattern="", const bool compare=false)
BenchmarkSuite * SetCurrentSuite (BenchmarkSuite *suite)
BenchmarkSuite * SetCurrentSuite (const std::string &name)
BenchmarkSuite * SetCurrentSuiteToParent ()
Static Public Member Functions
static BenchmarkSuite * GetMasterSuite ()
Private Attributes
std::map< std::string,
BenchmarkSuite * > child_suits
std::map< std::string,
std::list< BenchmarkCase * > > children
BenchmarkSuite * current_benchmark_suite
std::string name
BenchmarkSuite * parent
Detailed Description
Definition at line 26 of file benchmark_suite.hpp.
Constructor & Destructor Documentation
manak::BenchmarkSuite::BenchmarkSuite () inline
Definition at line 29 of file benchmark_suite.hpp.
Referenced by SetCurrentSuite().
manak::BenchmarkSuite::BenchmarkSuite (const std::string & name) inline
Definition at line 33 of file benchmark_suite.hpp.
manak::BenchmarkSuite::~BenchmarkSuite () inline
Definition at line 240 of file benchmark_suite.hpp.
References child_suits, and children.
Member Function Documentation
BenchmarkCase* manak::BenchmarkSuite::AddCase (BenchmarkCase * obj) inline
Definition at line 84 of file benchmark_suite.hpp.
References children, manak::BenchmarkCase::LibraryName(), and manak::BenchmarkCase::Name().
BenchmarkSuite* manak::BenchmarkSuite::AddSuite (BenchmarkSuite * suite) inline
Definition at line 108 of file benchmark_suite.hpp.
References child_suits, Name(), and parent.
Referenced by SetCurrentSuite().
bool manak::BenchmarkSuite::Find (const std::string & name, std::list< BenchmarkCase * > & lbc) inline
Definition at line 157 of file benchmark_suite.hpp.
References child_suits, and children.
Referenced by LoadData().
BenchmarkSuite* manak::BenchmarkSuite::GetCurrentSuite () const inline
Definition at line 44 of file benchmark_suite.hpp.
References current_benchmark_suite.
static BenchmarkSuite* manak::BenchmarkSuite::GetMasterSuite () inline static
Definition at line 38 of file benchmark_suite.hpp.
Referenced by manak::DeRegisterBenchmarkSuite::DeRegisterBenchmarkSuite(), manak::init_benchmarking_module(), manak::manak_benchmarking_main(), and manak::RegisterBenchmarkSuite::RegisterBenchmarkSuite().
bool manak::BenchmarkSuite::LoadData (const std::string & name) inline
Definition at line 181 of file benchmark_suite.hpp.
References Find(), and name.
Referenced by manak::manak_benchmarking_main().
const std::string& manak::BenchmarkSuite::Name () const inline
Definition at line 75 of file benchmark_suite.hpp.
References name.
Referenced by AddSuite(), and manak::init_benchmarking_module().
std::string& manak::BenchmarkSuite::Name () inline
Definition at line 79 of file benchmark_suite.hpp.
References name.
bool manak::BenchmarkSuite::Run (const std::string & uname = "", const std::string & pattern = "", const bool compare = false) inline
Definition at line 115 of file benchmark_suite.hpp.
References manak::utils::Log::Add(), child_suits, children, manak::utils::Log::GetLog(), and name.
Referenced by manak::manak_benchmarking_main().
BenchmarkSuite* manak::BenchmarkSuite::SetCurrentSuite (BenchmarkSuite * suite) inline
Definition at line 49 of file benchmark_suite.hpp.
References current_benchmark_suite.
Referenced by manak::RegisterBenchmarkSuite::RegisterBenchmarkSuite().
BenchmarkSuite* manak::BenchmarkSuite::SetCurrentSuite (const std::string & name) inline
Definition at line 54 of file benchmark_suite.hpp.
References AddSuite(), BenchmarkSuite(), child_suits, and current_benchmark_suite.
BenchmarkSuite* manak::BenchmarkSuite::SetCurrentSuiteToParent () inline
Definition at line 70 of file benchmark_suite.hpp.
References current_benchmark_suite, and parent.
Referenced by manak::DeRegisterBenchmarkSuite::DeRegisterBenchmarkSuite().
Member Data Documentation
std::map<std::string, BenchmarkSuite*> manak::BenchmarkSuite::child_suits private
Definition at line 259 of file benchmark_suite.hpp.
Referenced by AddSuite(), Find(), Run(), SetCurrentSuite(), and ~BenchmarkSuite().
std::map<std::string, std::list<BenchmarkCase*> > manak::BenchmarkSuite::children private
Definition at line 258 of file benchmark_suite.hpp.
Referenced by AddCase(), Find(), Run(), and ~BenchmarkSuite().
BenchmarkSuite* manak::BenchmarkSuite::current_benchmark_suite private
Definition at line 261 of file benchmark_suite.hpp.
Referenced by GetCurrentSuite(), SetCurrentSuite(), and SetCurrentSuiteToParent().
std::string manak::BenchmarkSuite::name private
Definition at line 256 of file benchmark_suite.hpp.
Referenced by LoadData(), Name(), and Run().
BenchmarkSuite* manak::BenchmarkSuite::parent private
Definition at line 262 of file benchmark_suite.hpp.
Referenced by AddSuite(), and SetCurrentSuiteToParent().
The documentation for this class was generated from the following file:
src/manak/benchmark_suit/benchmark_suite.hpp