Manak: manak::RunTree Class Reference
manak::RunTree Class Reference
Public Member Functions
RunTree ()
~RunTree ()
void AddCase (BenchmarkCase *bc)
void AddSuite (const std::string &name)
void CloseSuite ()
void LoadForComparison (std::istream &stream)
void PrintHTML (std::ostream &stream)
void PrintTXT (std::ostream &stream)
void Run ()
void SaveForComparison (std::ostream &stream)
Static Public Member Functions
static RunTree & GlobalRunTree ()
Private Attributes
std::string compare_time
size_t current_l_id
RNode * current_node
bool isComp
std::map< std::string, size_t > l_map
RNode * root
size_t total_nodes
Detailed Description
Definition at line 63 of file run_tree.hpp.
Constructor & Destructor Documentation
manak::RunTree::RunTree () inline
Definition at line 66 of file run_tree.hpp.
manak::RunTree::~RunTree () inline
Definition at line 75 of file run_tree.hpp.
References root.
Member Function Documentation
void manak::RunTree::AddCase (BenchmarkCase * bc)
void manak::RunTree::AddSuite (const std::string & name) inline
Definition at line 86 of file run_tree.hpp.
References manak::RNode::AddNext(), and current_node.
void manak::RunTree::CloseSuite () inline
Definition at line 93 of file run_tree.hpp.
References current_node, and manak::RNode::parent.
static RunTree& manak::RunTree::GlobalRunTree () inline static
Definition at line 80 of file run_tree.hpp.
Referenced by manak::manak_benchmarking_main().
void manak::RunTree::LoadForComparison (std::istream & stream)
Referenced by manak::manak_benchmarking_main().
void manak::RunTree::PrintHTML (std::ostream & stream)
Referenced by manak::manak_benchmarking_main().
void manak::RunTree::PrintTXT (std::ostream & stream)
Referenced by manak::manak_benchmarking_main().
void manak::RunTree::Run ()
Referenced by manak::manak_benchmarking_main().
void manak::RunTree::SaveForComparison (std::ostream & stream)
Referenced by manak::manak_benchmarking_main().
Member Data Documentation
std::string manak::RunTree::compare_time private
Definition at line 120 of file run_tree.hpp.
size_t manak::RunTree::current_l_id private
Definition at line 117 of file run_tree.hpp.
RNode* manak::RunTree::current_node private
Definition at line 112 of file run_tree.hpp.
Referenced by AddSuite(), and CloseSuite().
bool manak::RunTree::isComp private
Definition at line 119 of file run_tree.hpp.
std::map<std::string, size_t> manak::RunTree::l_map private
Definition at line 114 of file run_tree.hpp.
RNode* manak::RunTree::root private
Definition at line 111 of file run_tree.hpp.
Referenced by ~RunTree().
size_t manak::RunTree::total_nodes private
Definition at line 116 of file run_tree.hpp.
The documentation for this class was generated from the following file:
src/manak/benchmark_suit/run_tree.hpp