Manak: manak::Timer Class Reference
manak::Timer Class Reference
This class handles all the time related queries of libGDL.
Static Public Member Functions
static int & CIter ()
Get-set number of iterations.
static uint64_t & CTime ()
Get-set current timing.
static bool EndIter ()
Mark end of the iteration.
static PMeasure GetStats ()
Get statistics of current timer instance.
static std::string getTimeStamp (bool removeSpaces=false)
Returns current time-stamp as string.
static void Initialize (size_t iter)
Initialize a new Timer instance.
static size_t & Iterations ()
Get-set number.
static uint64_t & Max ()
Get-set max time.
static uint64_t microtimer ()
Returns the time in microseconds.
static uint64_t & Min ()
Get-set min time.
static void Reinitialize ()
Re initialize the current timer instance.
static void replaceAll (std::string &str, const std::string &from, const std::string &to)
Replace all occurrences.
static uint64_t & Start ()
Get-set start time.
static void StartIter ()
Mark start of the iteration.
static void StartTimer ()
Start timer.
static bool & StateIter ()
Get-set iteration state.
static bool & StateTimer ()
Get-set timer state.
static void StopTimer ()
Stop timer.
static uint64_t & TotalTime ()
Get-set total time.
Detailed Description
This class handles all the time related queries of libGDL.
Definition at line 81 of file timer.hpp.
Member Function Documentation
static int& manak::Timer::CIter () inline static
Get-set number of iterations.
Definition at line 282 of file timer.hpp.
Referenced by EndIter(), Initialize(), and Reinitialize().
static uint64_t& manak::Timer::CTime () inline static
Get-set current timing.
Definition at line 248 of file timer.hpp.
Referenced by EndIter(), StartIter(), and StopTimer().
static bool manak::Timer::EndIter () inline static
Mark end of the iteration.
Definition at line 216 of file timer.hpp.
References CIter(), CTime(), Max(), Min(), StateIter(), and TotalTime().
Referenced by manak::BenchmarkCase::Run().
static PMeasure manak::Timer::GetStats () inline static
Get statistics of current timer instance.
Definition at line 235 of file timer.hpp.
References Iterations(), Max(), Min(), and TotalTime().
Referenced by manak::BenchmarkCase::Run().
static std::string manak::Timer::getTimeStamp (bool removeSpaces = false) inline static
Returns current time-stamp as string.
Returns
std::string
Definition at line 158 of file timer.hpp.
References replaceAll().
Referenced by manak::utils::Log::Print().
static void manak::Timer::Initialize (size_t iter) inline static
Initialize a new Timer instance.
Definition at line 170 of file timer.hpp.
References CIter(), Iterations(), Max(), Min(), and TotalTime().
Referenced by manak::BenchmarkCase::Run().
static size_t& manak::Timer::Iterations () inline static
Get-set number.
Definition at line 275 of file timer.hpp.
Referenced by GetStats(), Initialize(), and Reinitialize().
static uint64_t& manak::Timer::Max () inline static
Get-set max time.
Definition at line 268 of file timer.hpp.
Referenced by EndIter(), GetStats(), Initialize(), and Reinitialize().
static uint64_t manak::Timer::microtimer () inline static
Returns the time in microseconds.
Returns
uint64_t Time in microseconds
Definition at line 89 of file timer.hpp.
Referenced by StartTimer(), and StopTimer().
static uint64_t& manak::Timer::Min () inline static
Get-set min time.
Definition at line 262 of file timer.hpp.
Referenced by EndIter(), GetStats(), Initialize(), and Reinitialize().
static void manak::Timer::Reinitialize () inline static
Re initialize the current timer instance.
Definition at line 180 of file timer.hpp.
References CIter(), Iterations(), Max(), Min(), and TotalTime().
static void manak::Timer::replaceAll (std::string & str, const std::string & from, const std::string & to) inline static
Replace all occurrences.
Definition at line 137 of file timer.hpp.
Referenced by getTimeStamp().
static uint64_t& manak::Timer::Start () inline static
Get-set start time.
Definition at line 255 of file timer.hpp.
Referenced by StartTimer(), and StopTimer().
static void manak::Timer::StartIter () inline static
Mark start of the iteration.
Definition at line 189 of file timer.hpp.
References CTime(), and StateIter().
Referenced by manak::BenchmarkCase::Run().
static void manak::Timer::StartTimer () inline static
Start timer.
Definition at line 196 of file timer.hpp.
References microtimer(), Start(), StateIter(), and StateTimer().
Referenced by manak::BenchmarkCase::Run().
static bool& manak::Timer::StateIter () inline static
Get-set iteration state.
Definition at line 289 of file timer.hpp.
Referenced by EndIter(), StartIter(), and StartTimer().
static bool& manak::Timer::StateTimer () inline static
Get-set timer state.
Definition at line 296 of file timer.hpp.
Referenced by StartTimer(), and StopTimer().
static void manak::Timer::StopTimer () inline static
Stop timer.
Definition at line 206 of file timer.hpp.
References CTime(), microtimer(), Start(), and StateTimer().
Referenced by manak::BenchmarkCase::Run().
static uint64_t& manak::Timer::TotalTime () inline static
Get-set total time.
Definition at line 241 of file timer.hpp.
Referenced by EndIter(), GetStats(), Initialize(), and Reinitialize().
The documentation for this class was generated from the following file:
src/manak/util/timer.hpp