Manak: manak::TManakCase< Case, RType, Args > Class Template Reference
manak::TManakCase< Case, RType, Args > Class Template Reference
Public Member Functions
TManakCase ()
TManakCase (const std::string &name, const std::string &library_name, std::function< RType(Args...)> t_function, double tolerance, const size_t iterations, double success_p)
TManakCase * AddArgs (Args...args)
TManakCase * AddArgs_N (const std::string &name, Args...args)
template<typename T , typename... Args2>
TManakCase * AddCustomArgs (T fun, Args2...params)
template<typename... Args2>
TManakCase * AddCustomArgs (std::list< std::tuple< Args...>>(&fun)(Args2...), Args2...params)
template<typename ST , typename... Args2>
TManakCase * AddCustomArgs_N (std::list< std::tuple< ST, Args...>>(&fun)(Args2...), Args2...params)
Private Attributes
size_t iter
std::function< RType(Args...)> t_function
Detailed Description
template<class Case, typename RType, typename... Args>
class manak::TManakCase< Case, RType, Args >
Definition at line 8 of file t_manak_case.hpp.
Constructor & Destructor Documentation
template<class Case , typename RType , typename... Args> manak::TManakCase< Case, RType, Args >::TManakCase () inline
Definition at line 11 of file t_manak_case.hpp.
template<class Case , typename RType , typename... Args> manak::TManakCase< Case, RType, Args >::TManakCase (const std::string & name, const std::string & library_name, std::function< RType(Args...)> t_function, double tolerance, const size_t iterations, double success_p) inline
Definition at line 14 of file t_manak_case.hpp.
Member Function Documentation
template<class Case , typename RType , typename... Args> TManakCase* manak::TManakCase< Case, RType, Args >::AddArgs (Args... args) inline
Definition at line 26 of file t_manak_case.hpp.
References manak::utils::Caller(), and manak::TManakCase< Case, RType, Args >::t_function.
template<class Case , typename RType , typename... Args> TManakCase* manak::TManakCase< Case, RType, Args >::AddArgs_N (const std::string & name, Args... args) inline
Definition at line 33 of file t_manak_case.hpp.
References manak::utils::Caller(), and manak::TManakCase< Case, RType, Args >::t_function.
template<class Case , typename RType , typename... Args> template<typename T , typename... Args2> TManakCase* manak::TManakCase< Case, RType, Args >::AddCustomArgs (T fun, Args2... params) inline
Definition at line 41 of file t_manak_case.hpp.
References manak::utils::BindToObject(), and manak::utils::Caller().
template<class Case , typename RType , typename... Args> template<typename... Args2> TManakCase* manak::TManakCase< Case, RType, Args >::AddCustomArgs (std::list< std::tuple< Args...>>(&)(Args2...) fun, Args2... params) inline
Definition at line 52 of file t_manak_case.hpp.
References manak::utils::BindToObject(), and manak::utils::Caller().
template<class Case , typename RType , typename... Args> template<typename ST , typename... Args2> TManakCase* manak::TManakCase< Case, RType, Args >::AddCustomArgs_N (std::list< std::tuple< ST, Args...>>(&)(Args2...) fun, Args2... params) inline
Definition at line 63 of file t_manak_case.hpp.
References manak::utils::BindToObject(), and manak::utils::Caller().
Member Data Documentation
template<class Case , typename RType , typename... Args> size_t manak::TManakCase< Case, RType, Args >::iter private
Definition at line 75 of file t_manak_case.hpp.
template<class Case , typename RType , typename... Args> std::function<RType(Args...)> manak::TManakCase< Case, RType, Args >::t_function private
Definition at line 74 of file t_manak_case.hpp.
Referenced by manak::TManakCase< Case, RType, Args >::AddArgs(), and manak::TManakCase< Case, RType, Args >::AddArgs_N().
The documentation for this class was generated from the following file:
src/manak/manak_suite/t_manak_case.hpp