Manak: manak::BenchmarkCase Class Reference
manak::BenchmarkCase Class Reference
Public Member Functions
BenchmarkCase (const std::string &name, const std::string &library_name, const size_t iterations=MANAK_DEFAULT_ITERATIONS, double tolerance=MANAK_DEFAULT_TOLERANCE, const std::string &desc="")
template<typename T >
BenchmarkCase (const std::string &name, const std::string &library_name, std::function< T()> run_function, const size_t iterations=MANAK_DEFAULT_ITERATIONS, double tolerance=MANAK_DEFAULT_TOLERANCE, const std::string &desc="")
template<typename T >
BenchmarkCase (const std::string &name, const std::string &library_name, T(run_function)(), const size_t iterations=MANAK_DEFAULT_ITERATIONS, double tolerance=MANAK_DEFAULT_TOLERANCE, const std::string &desc="")
void AddComparisonEntry (double d)
const std::string & LibraryName () const
const std::string & Name () const
std::list< utils::ObjectStore > Run ()
const std::string & UName () const
std::string & UName ()
Protected Attributes
std::string desc
size_t iterations
std::string library_name
std::string name
std::list< std::pair
< std::string, std::function
< void()> > > run_functions
std::vector< double > to_c
double tolerance
std::string uname
Detailed Description
Definition at line 32 of file benchmark_case.hpp.
Constructor & Destructor Documentation
manak::BenchmarkCase::BenchmarkCase (const std::string & name, const std::string & library_name, const size_t iterations = MANAK_DEFAULT_ITERATIONS, double tolerance = MANAK_DEFAULT_TOLERANCE, const std::string & desc = "") inline
Definition at line 35 of file benchmark_case.hpp.
template<typename T > manak::BenchmarkCase::BenchmarkCase (const std::string & name, const std::string & library_name, std::function< T()> run_function, const size_t iterations = MANAK_DEFAULT_ITERATIONS, double tolerance = MANAK_DEFAULT_TOLERANCE, const std::string & desc = "") inline
Definition at line 48 of file benchmark_case.hpp.
References run_functions.
template<typename T > manak::BenchmarkCase::BenchmarkCase (const std::string & name, const std::string & library_name, T(run_function)() , const size_t iterations = MANAK_DEFAULT_ITERATIONS, double tolerance = MANAK_DEFAULT_TOLERANCE, const std::string & desc = "") inline
Definition at line 64 of file benchmark_case.hpp.
References run_functions.
Member Function Documentation
void manak::BenchmarkCase::AddComparisonEntry (double d) inline
Definition at line 82 of file benchmark_case.hpp.
References to_c.
const std::string& manak::BenchmarkCase::LibraryName () const inline
Definition at line 92 of file benchmark_case.hpp.
References library_name.
Referenced by manak::BenchmarkSuite::AddCase().
const std::string& manak::BenchmarkCase::Name () const inline
Definition at line 87 of file benchmark_case.hpp.
References name.
Referenced by manak::BenchmarkSuite::AddCase().
std::list<utils::ObjectStore> manak::BenchmarkCase::Run ()
const std::string& manak::BenchmarkCase::UName () const inline
Definition at line 96 of file benchmark_case.hpp.
References uname.
std::string& manak::BenchmarkCase::UName () inline
Definition at line 100 of file benchmark_case.hpp.
References uname.
Member Data Documentation
std::string manak::BenchmarkCase::desc protected
Definition at line 110 of file benchmark_case.hpp.
size_t manak::BenchmarkCase::iterations protected
Definition at line 113 of file benchmark_case.hpp.
std::string manak::BenchmarkCase::library_name protected
Definition at line 109 of file benchmark_case.hpp.
Referenced by LibraryName().
std::string manak::BenchmarkCase::name protected
Definition at line 107 of file benchmark_case.hpp.
Referenced by Name().
std::list<std::pair<std::string, std::function<void()> > > manak::BenchmarkCase::run_functions protected
Definition at line 111 of file benchmark_case.hpp.
Referenced by manak::T_Benchmark_Case< RType, Args >::AddArgs(), manak::T_Benchmark_Case< RType, Args >::AddArgs_N(), and BenchmarkCase().
std::vector<double> manak::BenchmarkCase::to_c protected
Definition at line 115 of file benchmark_case.hpp.
Referenced by AddComparisonEntry().
double manak::BenchmarkCase::tolerance protected
Definition at line 112 of file benchmark_case.hpp.
std::string manak::BenchmarkCase::uname protected
Definition at line 108 of file benchmark_case.hpp.
Referenced by UName().
The documentation for this class was generated from the following file:
src/manak/benchmark_suit/benchmark_case.hpp