Manak: manak::T_Benchmark_Case< RType, Args > Class Template Reference
manak::T_Benchmark_Case< RType, Args > Class Template Reference
Public Member Functions
T_Benchmark_Case ()
T_Benchmark_Case (const std::string &name, const std::string &library_name, std::function< RType(Args...)> t_function, const size_t iterations=MANAK_DEFAULT_ITERATIONS, double tolerance=MANAK_DEFAULT_TOLERANCE, const std::string &desc="")
T_Benchmark_Case< RType, Args...> * AddArgs (Args...args)
T_Benchmark_Case * AddArgs_N (const std::string &name, Args...args)
template<typename... Args2>
T_Benchmark_Case * AddCustomArgs (std::function< std::list< std::tuple< Args...>>(Args2...)> fun, Args2...params)
template<typename... Args2>
T_Benchmark_Case * AddCustomArgs (std::list< std::tuple< Args...>>(&fun)(Args2...), Args2...params)
template<typename ST , typename... Args2>
T_Benchmark_Case * AddCustomArgs_N (std::list< std::tuple< ST, Args...>>(&fun)(Args2...), Args2...params)
Public Member Functions inherited from manak::BenchmarkCase
BenchmarkCase (const std::string &name, const std::string &library_name, const size_t iterations=MANAK_DEFAULT_ITERATIONS, double tolerance=MANAK_DEFAULT_TOLERANCE, const std::string &desc="")
template<typename T >
BenchmarkCase (const std::string &name, const std::string &library_name, std::function< T()> run_function, const size_t iterations=MANAK_DEFAULT_ITERATIONS, double tolerance=MANAK_DEFAULT_TOLERANCE, const std::string &desc="")
template<typename T >
BenchmarkCase (const std::string &name, const std::string &library_name, T(run_function)(), const size_t iterations=MANAK_DEFAULT_ITERATIONS, double tolerance=MANAK_DEFAULT_TOLERANCE, const std::string &desc="")
void AddComparisonEntry (double d)
const std::string & LibraryName () const
const std::string & Name () const
std::list< utils::ObjectStore > Run ()
const std::string & UName () const
std::string & UName ()
Private Attributes
size_t iter
std::function< RType(Args...)> t_function
Additional Inherited Members
Protected Attributes inherited from manak::BenchmarkCase
std::string desc
size_t iterations
std::string library_name
std::string name
std::list< std::pair
< std::string, std::function
< void()> > > run_functions
std::vector< double > to_c
double tolerance
std::string uname
Detailed Description
template<typename RType, typename... Args>
class manak::T_Benchmark_Case< RType, Args >
Definition at line 119 of file benchmark_case.hpp.
Constructor & Destructor Documentation
template<typename RType , typename... Args> manak::T_Benchmark_Case< RType, Args >::T_Benchmark_Case () inline
Definition at line 122 of file benchmark_case.hpp.
template<typename RType , typename... Args> manak::T_Benchmark_Case< RType, Args >::T_Benchmark_Case (const std::string & name, const std::string & library_name, std::function< RType(Args...)> t_function, const size_t iterations = MANAK_DEFAULT_ITERATIONS, double tolerance = MANAK_DEFAULT_TOLERANCE, const std::string & desc = "") inline
Definition at line 125 of file benchmark_case.hpp.
Member Function Documentation
template<typename RType , typename... Args> T_Benchmark_Case<RType, Args...>* manak::T_Benchmark_Case< RType, Args >::AddArgs (Args... args) inline
Definition at line 137 of file benchmark_case.hpp.
References manak::utils::Caller(), manak::BenchmarkCase::run_functions, and manak::T_Benchmark_Case< RType, Args >::t_function.
template<typename RType , typename... Args> T_Benchmark_Case* manak::T_Benchmark_Case< RType, Args >::AddArgs_N (const std::string & name, Args... args) inline
Definition at line 144 of file benchmark_case.hpp.
References manak::utils::Caller(), manak::BenchmarkCase::run_functions, and manak::T_Benchmark_Case< RType, Args >::t_function.
template<typename RType , typename... Args> template<typename... Args2> T_Benchmark_Case* manak::T_Benchmark_Case< RType, Args >::AddCustomArgs (std::function< std::list< std::tuple< Args...>>(Args2...)> fun, Args2... params) inline
Definition at line 152 of file benchmark_case.hpp.
References manak::utils::BindToObject(), and manak::utils::Caller().
template<typename RType , typename... Args> template<typename... Args2> T_Benchmark_Case* manak::T_Benchmark_Case< RType, Args >::AddCustomArgs (std::list< std::tuple< Args...>>(&)(Args2...) fun, Args2... params) inline
Definition at line 163 of file benchmark_case.hpp.
References manak::utils::BindToObject(), and manak::utils::Caller().
template<typename RType , typename... Args> template<typename ST , typename... Args2> T_Benchmark_Case* manak::T_Benchmark_Case< RType, Args >::AddCustomArgs_N (std::list< std::tuple< ST, Args...>>(&)(Args2...) fun, Args2... params) inline
Definition at line 174 of file benchmark_case.hpp.
References manak::utils::BindToObject(), and manak::utils::Caller().
Member Data Documentation
template<typename RType , typename... Args> size_t manak::T_Benchmark_Case< RType, Args >::iter private
Definition at line 186 of file benchmark_case.hpp.
template<typename RType , typename... Args> std::function<RType(Args...)> manak::T_Benchmark_Case< RType, Args >::t_function private
Definition at line 185 of file benchmark_case.hpp.
Referenced by manak::T_Benchmark_Case< RType, Args >::AddArgs(), and manak::T_Benchmark_Case< RType, Args >::AddArgs_N().
The documentation for this class was generated from the following file:
src/manak/benchmark_suit/benchmark_case.hpp