Manak: manak::ManakSuite Class Reference
manak::ManakSuite Class Reference
Public Member Functions
ManakSuite ()
ManakSuite (const std::string &name)
MANAK_INLINE ~ManakSuite ()
MANAK_INLINE ManakCase * AddCase (ManakCase *obj)
template<typename T , typename... Args>
bool AddGroup (Args...args)
ManakSuite * AddSuite (ManakSuite *suite)
MANAK_INLINE bool Find (const std::string &name, std::list< ManakCase * > &lbc)
ManakSuite * GetCurrentSuite () const
MANAK_INLINE bool LoadData (const std::string &name)
const std::string & Name () const
std::string & Name ()
MANAK_INLINE bool Run (const std::string &uname="", const std::string &pattern="", const bool compare=false)
ManakSuite * SetCurrentSuite (ManakSuite *suite)
MANAK_INLINE ManakSuite * SetCurrentSuite (const std::string &name)
ManakSuite * SetCurrentSuiteToParent ()
const std::string & UName () const
std::string & UName ()
Static Public Member Functions
static ManakSuite & GetMasterSuite ()
Private Attributes
std::map< std::string,
ManakSuite * > child_suits
std::map< std::string,
std::list< ManakCase * > > children
ManakSuite * current_manak_suite
std::string name
ManakSuite * parent
std::string uname
Detailed Description
Definition at line 19 of file manak_suite.hpp.
Constructor & Destructor Documentation
manak::ManakSuite::ManakSuite () inline
Definition at line 22 of file manak_suite.hpp.
manak::ManakSuite::ManakSuite (const std::string & name) inline
Definition at line 26 of file manak_suite.hpp.
MANAK_INLINE manak::ManakSuite::~ManakSuite ()
Member Function Documentation
MANAK_INLINE ManakCase* manak::ManakSuite::AddCase (ManakCase * obj)
Referenced by AddGroup().
template<typename T , typename... Args> bool manak::ManakSuite::AddGroup (Args... args) inline
Definition at line 74 of file manak_suite.hpp.
References AddCase().
ManakSuite* manak::ManakSuite::AddSuite (ManakSuite * suite) inline
Definition at line 47 of file manak_suite.hpp.
References child_suits, Name(), and parent.
MANAK_INLINE bool manak::ManakSuite::Find (const std::string & name, std::list< ManakCase * > & lbc)
ManakSuite* manak::ManakSuite::GetCurrentSuite () const inline
Definition at line 54 of file manak_suite.hpp.
References current_manak_suite.
static ManakSuite& manak::ManakSuite::GetMasterSuite () inline static
Definition at line 41 of file manak_suite.hpp.
Referenced by manak::DeRegisterManakSuite::DeRegisterManakSuite(), and manak::RegisterManakSuite::RegisterManakSuite().
MANAK_INLINE bool manak::ManakSuite::LoadData (const std::string & name)
const std::string& manak::ManakSuite::Name () const inline
Definition at line 87 of file manak_suite.hpp.
References name.
Referenced by AddSuite().
std::string& manak::ManakSuite::Name () inline
Definition at line 91 of file manak_suite.hpp.
References name.
MANAK_INLINE bool manak::ManakSuite::Run (const std::string & uname = "", const std::string & pattern = "", const bool compare = false)
ManakSuite* manak::ManakSuite::SetCurrentSuite (ManakSuite * suite) inline
Definition at line 59 of file manak_suite.hpp.
References current_manak_suite.
Referenced by manak::RegisterManakSuite::RegisterManakSuite().
MANAK_INLINE ManakSuite* manak::ManakSuite::SetCurrentSuite (const std::string & name)
ManakSuite* manak::ManakSuite::SetCurrentSuiteToParent () inline
Definition at line 66 of file manak_suite.hpp.
References current_manak_suite, and parent.
Referenced by manak::DeRegisterManakSuite::DeRegisterManakSuite().
const std::string& manak::ManakSuite::UName () const inline
Definition at line 95 of file manak_suite.hpp.
References uname.
std::string& manak::ManakSuite::UName () inline
Definition at line 99 of file manak_suite.hpp.
References uname.
Member Data Documentation
std::map<std::string, ManakSuite*> manak::ManakSuite::child_suits private
Definition at line 109 of file manak_suite.hpp.
Referenced by AddSuite().
std::map<std::string, std::list<ManakCase*> > manak::ManakSuite::children private
Definition at line 108 of file manak_suite.hpp.
ManakSuite* manak::ManakSuite::current_manak_suite private
Definition at line 111 of file manak_suite.hpp.
Referenced by GetCurrentSuite(), SetCurrentSuite(), and SetCurrentSuiteToParent().
std::string manak::ManakSuite::name private
Definition at line 105 of file manak_suite.hpp.
Referenced by Name().
ManakSuite* manak::ManakSuite::parent private
Definition at line 112 of file manak_suite.hpp.
Referenced by AddSuite(), and SetCurrentSuiteToParent().
std::string manak::ManakSuite::uname private
Definition at line 106 of file manak_suite.hpp.
Referenced by UName().
The documentation for this class was generated from the following file:
src/manak/manak_suite/manak_suite.hpp