Manak: manak::utils::Log Class Reference
manak::utils::Log Class Reference
This class stores and prints all the necessary information about the run.
Public Member Functions
Log ()
Create an empty Log.
CaseLogEntry & Add (const std::string &name, const std::string &uname)
Add a benchmark case to his log.
size_t AddLibrary (const std::string &name)
Add library to this log.
void Print (std::ostream &stream)
Print all the information in a user friendly way.
void Save (std::ostream &stream)
Save all the information to the file for comparison.
Static Public Member Functions
static Log & GetLog ()
Get singleton Log instance.
Private Attributes
size_t c_l_id
currently assigned library id.
std::list< CaseLogEntry > cases
List of benchamrk cases.
std::map< std::string, size_t > l_ids
map of library name to id
std::map< size_t, std::string > r_l_ids
map of library id to name
Detailed Description
This class stores and prints all the necessary information about the run.
Definition at line 202 of file log.hpp.
Constructor & Destructor Documentation
manak::utils::Log::Log () inline
Create an empty Log.
Definition at line 206 of file log.hpp.
Member Function Documentation
CaseLogEntry& manak::utils::Log::Add (const std::string & name, const std::string & uname) inline
Add a benchmark case to his log.
Definition at line 217 of file log.hpp.
References cases.
Referenced by manak::BenchmarkSuite::Run().
size_t manak::utils::Log::AddLibrary (const std::string & name) inline
Add library to this log.
Definition at line 224 of file log.hpp.
References c_l_id, l_ids, and r_l_ids.
Referenced by manak::BenchmarkCase::Run().
static Log& manak::utils::Log::GetLog () inline static
Get singleton Log instance.
Definition at line 210 of file log.hpp.
Referenced by manak::manak_benchmarking_main(), manak::BenchmarkSuite::Run(), and manak::BenchmarkCase::Run().
void manak::utils::Log::Print (std::ostream & stream) inline
Print all the information in a user friendly way.
Definition at line 238 of file log.hpp.
References __MANAK_VERSION_MAJOR, __MANAK_VERSION_MINOR, __MANAK_VERSION_PATCH, cases, manak::Timer::getTimeStamp(), l_ids, and r_l_ids.
Referenced by manak::manak_benchmarking_main().
void manak::utils::Log::Save (std::ostream & stream) inline
Save all the information to the file for comparison.
Definition at line 274 of file log.hpp.
References cases, l_ids, and r_l_ids.
Referenced by manak::manak_benchmarking_main().
Member Data Documentation
size_t manak::utils::Log::c_l_id private
currently assigned library id.
Definition at line 301 of file log.hpp.
Referenced by AddLibrary().
std::list<CaseLogEntry> manak::utils::Log::cases private
List of benchamrk cases.
Definition at line 298 of file log.hpp.
Referenced by Add(), Print(), and Save().
std::map<std::string, size_t> manak::utils::Log::l_ids private
map of library name to id
Definition at line 294 of file log.hpp.
Referenced by AddLibrary(), Print(), and Save().
std::map<size_t, std::string> manak::utils::Log::r_l_ids private
map of library id to name
Definition at line 296 of file log.hpp.
Referenced by AddLibrary(), Print(), and Save().
The documentation for this class was generated from the following file:
src/manak/util/log.hpp