Manak: manak::utils::helper Namespace Reference
manak::utils::helper Namespace Reference
Template Helper Functions.
Classes
struct Hold
struct SGenerate
struct SGenerate< 1 >
struct template_placeholder
Functions
template<typename RType , typename C , typename... Args>
std::function< RType(Args...)> BindToObject (RType(C::*fun)(Args...) const, const C *c)
template<typename RType , typename F , typename O , int... S>
RType BindToObject2 (F fun, const O *o, Hold< S...>)
template<typename RType , typename F , typename O , int... S>
RType BindToObject2 (F fun, O *o, Hold< S...>)
template<typename RType , typename Fun , typename P , int... S>
RType Caller_2 (Fun fun, P params, Hold< S...>)
Variables
template<int N, int... Args>
Hold< Args..., N > Combine (Hold< Args...>, Hold< N >)
Detailed Description
Template Helper Functions.
Function Documentation
template<typename RType , typename C , typename... Args> std::function<RType(Args...)> manak::utils::helper::BindToObject (RType(C::*)(Args...) const fun, const C * c)
Definition at line 89 of file template_utils.hpp.
References BindToObject2(), and manak::utils::helper::SGenerate< N >::type.
template<typename RType , typename F , typename O , int... S> RType manak::utils::helper::BindToObject2 (F fun, const O * o, Hold< S...>)
Definition at line 77 of file template_utils.hpp.
Referenced by BindToObject(), and manak::utils::BindToObject().
template<typename RType , typename F , typename O , int... S> RType manak::utils::helper::BindToObject2 (F fun, O * o, Hold< S...>)
Definition at line 83 of file template_utils.hpp.
template<typename RType , typename Fun , typename P , int... S> RType manak::utils::helper::Caller_2 (Fun fun, P params, Hold< S...>)
Definition at line 64 of file template_utils.hpp.
Variable Documentation
template<int N, int... Args> Hold<Args..., N> manak::utils::helper::Combine(Hold< Args...>, Hold< N >)
Definition at line 46 of file template_utils.hpp.