Manak: manak::utils Namespace Reference
manak::utils Namespace Reference
Useful Utilities.
Namespaces
cli
Command Line Interface.
helper
Template Helper Functions.
Classes
class ObjectStore
Functions
template<typename RType , typename C , typename... Args>
std::function< RType(Args...)> BindToObject (RType(C::*fun)(Args...), C *c)
template<typename RType , typename C , typename... Args>
std::function< RType(Args...)> BindToObject (RType(C::*fun)(Args...) const, const C *c)
template<typename RType , typename P , typename... Args>
RType Caller (std::function< RType(Args...)> fun, P params)
template<typename RType , typename P , typename... Args>
RType Caller (RType(*fun)(Args...), P params)
std::ostream & operator<< (std::ostream &s, const ObjectStore &os)
Detailed Description
Useful Utilities.
Function Documentation
template<typename RType , typename C , typename... Args> std::function< RType(Args...)> manak::utils::BindToObject (RType(C::*)(Args...) fun, C * c)
Definition at line 115 of file template_utils.hpp.
References manak::utils::helper::BindToObject2().
Referenced by manak::T_Benchmark_Case< RType, Args >::AddCustomArgs(), and manak::T_Benchmark_Case< RType, Args >::AddCustomArgs_N().
template<typename RType , typename C , typename... Args> std::function<RType(Args...)> manak::utils::BindToObject (RType(C::*)(Args...) const fun, const C * c)
Definition at line 121 of file template_utils.hpp.
References manak::utils::helper::BindToObject2().
template<typename RType , typename P , typename... Args> RType manak::utils::Caller (std::function< RType(Args...)> fun, P params)
Definition at line 96 of file template_utils.hpp.
Referenced by manak::T_Benchmark_Case< RType, Args >::AddArgs(), manak::T_Benchmark_Case< RType, Args >::AddArgs_N(), manak::T_Benchmark_Case< RType, Args >::AddCustomArgs(), and manak::T_Benchmark_Case< RType, Args >::AddCustomArgs_N().
template<typename RType , typename P , typename... Args> RType manak::utils::Caller (RType(*)(Args...) fun, P params)
Definition at line 108 of file template_utils.hpp.
std::ostream& manak::utils::operator<< (std::ostream & s, const ObjectStore & os)
Definition at line 84 of file object_store.hpp.