Manak: manak Namespace Reference
manak Namespace Reference
C++ Unit Benchmarking Library.
Namespaces
utils
Useful Utilities.
Classes
class BenchmarkCase
class BenchmarkSuite
class DeRegisterBenchmarkSuite
struct PMeasure
Stores the timing information of any run.
class RegisterBenchmarkSuite
struct RNode
class RunTree
class T_Benchmark_Case
class Timer
This class handles all the time related queries of libGDL.
Functions
template<typename RType , typename... Args>
T_Benchmark_Case< RType, Args...> * CTBenchmarkObject (const std::string &name, const std::string &library_name, const size_t iterations, double tolerance, const std::string &desc, RType(*fun)(Args...))
template<typename RType , typename... Args>
T_Benchmark_Case< RType, Args...> * CTBenchmarkObject (const std::string &name, const std::string &library_name, const size_t iterations, double tolerance, const std::string &desc, std::function< RType(Args...)> fun)
std::string GetVersionInfo ()
Returns the version information in string.
bool init_benchmarking_module ()
int manak_benchmarking_main (std::function< bool()> init_func, int argc, char *argv[])
This function runs benchmarking module with given function.
std::ostream & operator<< (std::ostream &stream, const PMeasure &pm)
Detailed Description
C++ Unit Benchmarking Library.
Function Documentation
template<typename RType , typename... Args> T_Benchmark_Case<RType, Args...>* manak::CTBenchmarkObject (const std::string & name, const std::string & library_name, const size_t iterations, double tolerance, const std::string & desc, RType(*)(Args...) fun)
Definition at line 190 of file benchmark_case.hpp.
template<typename RType , typename... Args> T_Benchmark_Case<RType, Args...>* manak::CTBenchmarkObject (const std::string & name, const std::string & library_name, const size_t iterations, double tolerance, const std::string & desc, std::function< RType(Args...)> fun)
Definition at line 201 of file benchmark_case.hpp.
std::string manak::GetVersionInfo ()
Returns the version information in string.
Definition at line 24 of file version.hpp.
References __MANAK_VERSION_MAJOR, __MANAK_VERSION_MINOR, __MANAK_VERSION_NAME, and __MANAK_VERSION_PATCH.
Referenced by manak_benchmarking_main().
bool manak::init_benchmarking_module ()
Definition at line 141 of file benchmark_suite.hpp.
References manak::BenchmarkSuite::GetMasterSuite(), MANAK_MODULE_NAME, and manak::BenchmarkSuite::Name().
int manak::manak_benchmarking_main (std::function< bool()> init_func, int argc, char * argv[])
This function runs benchmarking module with given function.
If main is set to auto, this function will be called else it has to be called manually. Returns status as int
Returns
int
Definition at line 27 of file manak.hpp.
References manak::utils::cli::CLI::cmdOptionExists(), manak::utils::cli::CLI::getCmdOption(), manak::BenchmarkSuite::GetMasterSuite(), GetVersionInfo(), manak::RunTree::GlobalRunTree(), manak::RunTree::LoadForComparison(), MANAK_DEFAULT_OUT_FILENAME, MANAK_STRINGIZE, manak::RunTree::PrintHTML(), manak::RunTree::PrintTXT(), manak::BenchmarkSuite::Run(), manak::RunTree::Run(), and manak::RunTree::SaveForComparison().
std::ostream& manak::operator<< (std::ostream & stream, const PMeasure & pm) inline
Definition at line 56 of file pmeasure.hpp.
References manak::PMeasure::avg.